### ISSUE TITLE
 [Windows Cryptography Next Generation (CNG) is not supported on this platform.] 

### ISSUE THREAD

**Issue by liguobao** [scottbrady91/AspNetCore-SignInWithApple-Example#2]
```c#
  var cngKey = CngKey.Import(Convert.FromBase64String(privateKey), CngKeyBlobFormat.Pkcs8PrivateBlob);
```

it will get fail message " [Windows Cryptography Next Generation (CNG) is not supported on this platform.] " on linux.

**Comment by liguobao** [comment]
https://github.com/dotnet/runtime/issues/21259

**Comment by scottbrady91** [comment]
Solved by switching to the newer `ImportPkcs8PrivateKey` method on `ECDsa`. https://github.com/scottbrady91/AspNetCore-SignInWithApple-Example/blob/main/ScottBrady91.SignInWithApple.Example/Startup.cs#L81

Confirmed working on Ubuntu 🙂
